export const opcionesMarca = [
  { value: "", label: "Selecciona una marca" },
  { value: "Acer", label: "Acer" },
  { value: "AKG", label: "AKG" },
  { value: "Alienware", label: "Alienware" },
  { value: "Apple", label: "Apple" },
  { value: "Apple AirPods", label: "Apple AirPods" },
  { value: "Apple iMac", label: "Apple iMac" },
  { value: "Asus", label: "Asus" },
  { value: "Aston Origin", label: "Aston Origin" },
  { value: "Audio-Technica", label: "Audio-Technica" },
  { value: "Beats by Dre", label: "Beats by Dre" },
  { value: "Behringer C-1", label: "Behringer C-1" },
  { value: "Bose", label: "Bose" },
  { value: "CAD Audio U37", label: "CAD Audio U37" },
  { value: "Corsair", label: "Corsair" },
  { value: "CyberPowerPC", label: "CyberPowerPC" },
  { value: "Dell", label: "Dell" },
  { value: "Electro-Voice RE20", label: "Electro-Voice RE20" },
  { value: "Google Pixel", label: "Google Pixel" },
  { value: "HP", label: "HP" },
  { value: "Huawei", label: "Huawei" },
  { value: "Huawei MateBook", label: "Huawei MateBook" },
  { value: "IPhone", label: "IPhone" },
  { value: "JBL", label: "JBL" },
  { value: "Lenovo", label: "Lenovo" },
  { value: "LG", label: "LG" },
  { value: "Marshall", label: "Marshall" },
  { value: "Microsoft Surface", label: "Microsoft Surface" },
  { value: "Microsoft Surface Studio", label: "Microsoft Surface Studio" },
  { value: "Motorola", label: "Motorola" },
  { value: "MSI", label: "MSI" },
  { value: "MXL 770", label: "MXL 770" },
  { value: "Neumann U87", label: "Neumann U87" },
  { value: "Nokia", label: "Nokia" },
  { value: "NZXT", label: "NZXT" },
  { value: "OnePlus", label: "OnePlus" },
  { value: "Oppo", label: "Oppo" },
  { value: "Panasonic", label: "Panasonic" },
  { value: "Philips", label: "Philips" },
  { value: "Plantronics", label: "Plantronics" },
  { value: "Razer", label: "Razer" },
  { value: "Realme", label: "Realme" },
  { value: "Rode NT-USB", label: "Rode NT-USB" },
  { value: "Samsung", label: "Samsung" },
  { value: "Samson Meteor", label: "Samson Meteor" },
  { value: "Sennheiser", label: "Sennheiser" },
  { value: "Sennheiser e835", label: "Sennheiser e835" },
  { value: "Shure", label: "Shure" },
  { value: "Shure SM58", label: "Shure SM58" },
  { value: "Skullcandy", label: "Skullcandy" },
  { value: "Sony", label: "Sony" },
  { value: "Toshiba", label: "Toshiba" },
  { value: "TP-Link", label: "TP-Link" },
  { value: "Vivo", label: "Vivo" },
  { value: "Xiaomi", label: "Xiaomi" },
  { value: "Zoom H5", label: "Zoom H5" },
  { value: "Zotac", label: "Zotac" },
];
